name: bolt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        repository: 'DaggupatiPavan/backstage-templates'
        # token: ${ secrets.gitlab-syam }
        ref: 'main'
    - name: Build Application
      uses: DaggupatiPavan/custom-action@v1
      id: build
      with:
        command: 'npm run build'
        
    - name: Use Build Output
      run: |
        echo "Build took ${{ steps.build.outputs.duration }}ms"
        echo "Build status: ${{ steps.build.outputs.status }}"
