name: Install Tools Workflow

on:
  push:
    branches:
      - main

jobs:
  setup-tools:
    runs-on: self-hosted   # Use a self-hosted Linux runner

    steps:
    # Step 1: Checkout code (you can skip this if you only want the tools installed)
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Install Java (OpenJDK 11)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin' 

    # Step 3: Install Node.js (Version 14)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    # Step 4: Install Docker (via Docker setup action)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 5: Install Maven (via setup-java action, which handles Maven automatically)
    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'   # Optional, change if you need another JDK distribution

    # Step 6: Install Python (Version 3.8)
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    # Optionally, verify installations by checking versions
    - name: Verify Java version
      run: java -version

    - name: Verify Node.js version
      run: node -v

    - name: Verify Docker version
      run: docker --version

    - name: Verify Maven version
      run: mvn -v

    - name: Verify Python version
      run: python --version
