name: Build and Dockerize Project

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GIT_REPO_URL: 'https://github.com/ramakanthdevidi/firstproject.git'
      CODE_DIR: 'firstproject'
      DOCKER_IMAGE: 'ramakanthreddy709/my-app:1.0'

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Clone Repository (if not already cloned)
      run: |
        if [ ! -d "$CODE_DIR" ]; then
          echo "Cloning repository..."
          git clone $GIT_REPO_URL
        else
          echo "Repository already exists. Skipping clone."
        fi

    - name: Build with Maven
      run: |
        cd $CODE_DIR
        echo "Building the project with Maven..."
        mvn clean package -Dmaven.test.failure.ignore=true

    - name: Build Docker image
      run: |
        cd $CODE_DIR
        echo "Building Docker image..."
        docker build -t $DOCKER_IMAGE .

    
