name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Clone Repository
      run: |
        git clone --branch main https://github.com/ramakanthdevidi/firstproject.git.

    - name: Maven Build
      run: mvn clean install

    - name: Build Docker Image
      run: |
        sudo chmod 666 /var/run/docker.sock
        docker build -t firstproject-image .

    - name: Run Docker Container
      run: |
        docker rm -f firstproject-container || true
        docker run -d --name firstproject-container firstproject-image

